name: math124-notebooks
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - jupyterlab
  - matplotlib
  - nbconvert
  - numpy
  - pandas
  - plotly
  - ipywidgets
  - pip:
      - otter-grader==6.1.6
